import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Umfangreiche Liste deutscher Ausbildungsberufe wie vom Benutzer bereitgestellt
const trainingProfessions = [
  // Klassische duale Berufsausbildung
  { name: 'Anlagenmechaniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Anlagenmechaniker/in für Sanitär-, Heizungs- und Klimatechnik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Automatenfachmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Automobilkaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Bäcker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Bankkaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Bauzeichner/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Berufskraftfahrer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Bestattungsfachkraft', category: 'Klassische duale Berufsausbildung' },
  { name: 'Buchhändler/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Bürokaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Chemielaborant/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Dachdecker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Einzelhandelskaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Elektroniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Elektroniker/in für Automatisierungstechnik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Elektroniker/in für Betriebstechnik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Elektroniker/in für Energie- und Gebäudetechnik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Elektroniker/in für Gebäude- und Infrastruktursysteme', category: 'Klassische duale Berufsausbildung' },
  { name: 'Elektroniker/in für Geräte und Systeme', category: 'Klassische duale Berufsausbildung' },
  { name: 'Elektroniker/in für Informations- und Systemtechnik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Elektroniker/in für Informations- und Telekommunikationstechnik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Elektroniker/in für Maschinen und Antriebstechnik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Energieelektroniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Erzieher/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachkraft für Lagerlogistik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachkraft für Lebensmitteltechnik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachkraft für Schutz und Sicherheit', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachkraft für Veranstaltungstechnik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachkraft für Wasserversorgungstechnik', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachkraft im Gastgewerbe', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachlagerist/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachmann/frau für Restaurants und Veranstaltungsgastronomie', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachmann/frau für Systemgastronomie', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachinformatiker/in Anwendungsentwicklung', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachinformatiker/in Daten- und Prozessanalyse', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachinformatiker/in Digitale Vernetzung', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fachinformatiker/in Systemintegration', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fahrzeuglackierer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Feinwerkmechaniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Fleischer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Florist/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Friseur/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Gärtner/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Gebäudereiniger/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Glasmacher/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Groß- und Außenhandelskaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Handwerker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Hauswirtschafter/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Heizungsbauer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Holzmechaniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Hotelfachmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Hotelkaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Immobilienkaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Industriekaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Industriemechaniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Informatikkaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'IT-System-Elektroniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'IT-System-Kaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Jugend- und Heimerzieher/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kälteanlagenbauer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für audiovisuelle Medien', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für Büromanagement', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für Digitalisierungsmanagement', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für E-Commerce', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für Groß- und Außenhandelsmanagement', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für IT-System-Management', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für Marketingkommunikation', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für Spedition und Logistikdienstleistung', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für Tourismus und Freizeit', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für Verkehrsservice', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau für Versicherungen und Finanzanlagen', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau im Einzelhandel', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kaufmann/frau im Gesundheitswesen', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kinderpfleger/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Koch/Köchin', category: 'Klassische duale Berufsausbildung' },
  { name: 'Konditor/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Konstruktionsmechaniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kosmetiker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Kraftfahrzeugmechatroniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Krankenpfleger/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Landwirt/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Logopäde/Logopädin', category: 'Klassische duale Berufsausbildung' },
  { name: 'Maler/in und Lackierer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Maschinen- und Anlagenführer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Maskenbildner/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Masseur/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Mathematisch-technische/r Softwareentwickler/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Maurer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Mechatroniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Mediengestalter/in Bild und Ton', category: 'Klassische duale Berufsausbildung' },
  { name: 'Mediengestalter/in Digital und Print', category: 'Klassische duale Berufsausbildung' },
  { name: 'Medienkaufmann/frau Digital und Print', category: 'Klassische duale Berufsausbildung' },
  { name: 'Medientechnologe/in Druck', category: 'Klassische duale Berufsausbildung' },
  { name: 'Medientechnologe/in Druckverarbeitung', category: 'Klassische duale Berufsausbildung' },
  { name: 'Medientechnologe/in Siebdruck', category: 'Klassische duale Berufsausbildung' },
  { name: 'Medizinische/r Fachangestellte/r', category: 'Klassische duale Berufsausbildung' },
  { name: 'Metallbauer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Microtechnologe/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Notarfachangestellte/r', category: 'Klassische duale Berufsausbildung' },
  { name: 'Optiker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Orthopädieschuhmacher/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Packmitteltechnologe/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Personaldienstleistungskaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Pferdewirt/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Pharmazeutisch-kaufmännische/r Angestellte/r', category: 'Klassische duale Berufsausbildung' },
  { name: 'Physiotherapeut/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Rechtsanwaltsfachangestellte/r', category: 'Klassische duale Berufsausbildung' },
  { name: 'Restaurantfachmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Rohrleitungsbauer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Schornsteinfeger/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Schreiner/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Servicekaufmann/frau im Luftverkehr', category: 'Klassische duale Berufsausbildung' },
  { name: 'Sozialversicherungsfachangestellte/r', category: 'Klassische duale Berufsausbildung' },
  { name: 'Sport- und Fitnesskaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Steuerfachangestellte/r', category: 'Klassische duale Berufsausbildung' },
  { name: 'Straßenbauer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Systemelektroniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Technische/r Produktdesigner/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Technische/r Systemplaner/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Technische/r Zeichner/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Textil- und Modenäher/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Textil- und Modeschneider/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Tierpfleger/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Tischler/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Tourismuskaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Veranstaltungskaufmann/frau', category: 'Klassische duale Berufsausbildung' },
  { name: 'Verkäufer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Verwaltungsfachangestellte/r', category: 'Klassische duale Berufsausbildung' },
  { name: 'Wasserbauer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Zahnmedizinische/r Fachangestellte/r', category: 'Klassische duale Berufsausbildung' },
  { name: 'Zahntechniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Zerspanungsmechaniker/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Zimmerer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Zweiradmechatroniker/in', category: 'Klassische duale Berufsausbildung' },

  // Duales Studium
  { name: 'Bauingenieurwesen (dual)', category: 'Duales Studium' },
  { name: 'Betriebswirtschaftslehre (dual)', category: 'Duales Studium' },
  { name: 'Elektrotechnik (dual)', category: 'Duales Studium' },
  { name: 'Informatik (dual)', category: 'Duales Studium' },
  { name: 'Ingenieurwesen (dual)', category: 'Duales Studium' },
  { name: 'Maschinenbau (dual)', category: 'Duales Studium' },
  { name: 'Medieninformatik (dual)', category: 'Duales Studium' },
  { name: 'Pflegemanagement (dual)', category: 'Duales Studium' },
  { name: 'Soziale Arbeit (dual)', category: 'Duales Studium' },
  { name: 'Wirtschaftsinformatik (dual)', category: 'Duales Studium' },
  { name: 'Wirtschaftsingenieurwesen (dual)', category: 'Duales Studium' },

  // Schulische Ausbildung
  { name: 'Altenpfleger/in', category: 'Schulische Ausbildung' },
  { name: 'Diätassistent/in', category: 'Schulische Ausbildung' },
  { name: 'Ergotherapeut/in', category: 'Schulische Ausbildung' },
  { name: 'Gesundheits- und Krankenpfleger/in', category: 'Schulische Ausbildung' },
  { name: 'Gesundheits- und Kinderkrankenpfleger/in', category: 'Schulische Ausbildung' },
  { name: 'Hebamme/Entbindungspfleger', category: 'Schulische Ausbildung' },
  { name: 'Heilerziehungspfleger/in', category: 'Schulische Ausbildung' },
  { name: 'Logopäde/Logopädin', category: 'Schulische Ausbildung' },
  { name: 'Masseur/in und medizinische/r Bademeister/in', category: 'Schulische Ausbildung' },
  { name: 'Medizinisch-technische/r Assistent/in für Funktionsdiagnostik', category: 'Schulische Ausbildung' },
  { name: 'Medizinisch-technische/r Laboratoriumsassistent/in', category: 'Schulische Ausbildung' },
  { name: 'Medizinisch-technische/r Radiologieassistent/in', category: 'Schulische Ausbildung' },
  { name: 'Notfallsanitäter/in', category: 'Schulische Ausbildung' },
  { name: 'Operationstechnische/r Assistent/in', category: 'Schulische Ausbildung' },
  { name: 'Orthoptist/in', category: 'Schulische Ausbildung' },
  { name: 'Pharmazeutisch-technische/r Assistent/in', category: 'Schulische Ausbildung' },
  { name: 'Physiotherapeut/in', category: 'Schulische Ausbildung' },
  { name: 'Podologe/Podologin', category: 'Schulische Ausbildung' },
  { name: 'Rettungsassistent/in', category: 'Schulische Ausbildung' },
  { name: 'Sozialpädagogische/r Assistent/in', category: 'Schulische Ausbildung' },
  { name: 'Veterinärmedizinisch-technische/r Assistent/in', category: 'Schulische Ausbildung' },

  // Weiterbildung/Fortbildung
  { name: 'Betriebswirt/in', category: 'Weiterbildung/Fortbildung' },
  { name: 'Fachwirt/in', category: 'Weiterbildung/Fortbildung' },
  { name: 'Industriemeister/in', category: 'Weiterbildung/Fortbildung' },
  { name: 'Meister/in', category: 'Weiterbildung/Fortbildung' },
  { name: 'Staatlich geprüfte/r Betriebswirt/in', category: 'Weiterbildung/Fortbildung' },
  { name: 'Staatlich geprüfte/r Techniker/in', category: 'Weiterbildung/Fortbildung' },
  { name: 'Technische/r Betriebswirt/in', category: 'Weiterbildung/Fortbildung' },

  // Zusätzliche IT-Berufe für moderne Entwicklung
  { name: 'Kaufmann/frau für IT-Systemmanagement', category: 'Klassische duale Berufsausbildung' },
  { name: 'IT-System-Manager/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Datenbankspezialist/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Netzwerkadministrator/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Webentwickler/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Software-Entwickler/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'App-Entwickler/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Game-Developer', category: 'Klassische duale Berufsausbildung' },
  { name: 'DevOps-Engineer', category: 'Klassische duale Berufsausbildung' },
  { name: 'Cloud-Architekt/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Cybersecurity-Spezialist/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Data-Scientist', category: 'Klassische duale Berufsausbildung' },
  { name: 'Machine Learning Engineer', category: 'Klassische duale Berufsausbildung' },
  { name: 'UI/UX-Designer/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Product Manager/in (IT)', category: 'Klassische duale Berufsausbildung' },

  // Weitere moderne Berufe
  { name: 'E-Commerce-Manager/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Digital Marketing Manager/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Social Media Manager/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Content Manager/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Online-Redakteur/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'SEO-Spezialist/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Influencer Marketing Manager/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Performance Marketing Manager/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'CRM-Manager/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Business Analyst', category: 'Klassische duale Berufsausbildung' },
  { name: 'Projektmanager/in', category: 'Klassische duale Berufsausbildung' },
  { name: 'Scrum Master', category: 'Klassische duale Berufsausbildung' },
  { name: 'Agile Coach', category: 'Klassische duale Berufsausbildung' },
];

async function main() {
  console.log('Start seeding training professions...');
  
  // Lösche alle bestehenden Einträge
  await prisma.trainingProfession.deleteMany({});
  console.log('Deleted existing training professions');
  
  // Erstelle alle Ausbildungsberufe mit upsert um Duplikate zu vermeiden
  for (const profession of trainingProfessions) {
    await prisma.trainingProfession.upsert({
      where: { name: profession.name },
      update: { category: profession.category },
      create: profession,
    });
  }
  
  console.log(`Seeded ${trainingProfessions.length} training professions`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });